server {
    server_name admin.wobbly.site;

    location = / {
        return 307 /production/;
    }

    location = /production {
        return 307 /production/;
    }

    location = /staging {
        return 307 /staging/;
    }

    location = /production/ {
        root /opt/wobbly-front-production/current;
        try_files /index.html =404;
    }

    location = /staging/ {
        root /opt/wobbly-front-staging/current;
        try_files /index.html =404;
    }

    location /production/api/ {
        rewrite ^/production/api/(.*)$ /admin/$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /staging/api/ {
        rewrite ^/staging/api/(.*)$ /admin/$1 break;
        proxy_pass http://127.0.0.1:8001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /production/assets/ {
        alias /opt/wobbly-front-production/current/assets/;
        try_files $uri =404;
    }

    location /production/og/ {
        alias /opt/wobbly-front-production/current/og/;
        try_files $uri =404;
    }

    location /staging/assets/ {
        alias /opt/wobbly-front-staging/current/assets/;
        try_files $uri =404;
    }

    location /staging/og/ {
        alias /opt/wobbly-front-staging/current/og/;
        try_files $uri =404;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/admin.wobbly.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/admin.wobbly.site/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.wobbly.site;
    return 301 https://$host$request_uri;
}
